spring:
    rabbitmq:
        host: rabbitmq
        port: 5672
        username: guest
        password: guest
    cloud:
        stream:
            bindings:
                verbfunction-in-0:
                    destination: verbrequest
                verbfunction-out-0:
                    destination: verbresponse
