spring:
    kafka:
        bootstrap-servers: kafka:9092
    cloud:
        stream:
            bindings:
                verbfunction-in-0:
                    destination: verbrequest
                verbfunction-out-0:
                    destination: verbresponse
